# Generated by Django 5.0.6 on 2024-07-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
