# Generated by Django 5.0.6 on 2024-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_video_link_alter_video_video_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_link",
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
