# Generated by Django 5.0.6 on 2024-07-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_video_video_link_alter_video_video_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_link",
            new_name="youtube_link",
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_file",
        ),
    ]
