# Generated by Django 5.0.6 on 2024-07-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_rename_video_link_video_youtube_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="youtube_link",
            new_name="google_drive_link",
        ),
    ]
