# Generated by Django 5.0.6 on 2024-07-28 06:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_rename_youtube_link_video_google_drive_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="abstract",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
