# Generated by Django 5.0.7 on 2024-07-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autobiography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="autobiography/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
