# Generated by Django 5.0.7 on 2024-07-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autobiography", "0002_trial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Trial",
        ),
        migrations.AddField(
            model_name="autobiography",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="autobiography/"),
        ),
    ]
