# Generated by Django 5.0.7 on 2024-07-13 06:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("autobiography", "0003_delete_trial_autobiography_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autobiography",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
