# Generated by Django 5.0.7 on 2024-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0002_alter_photoessay_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photoessay",
            old_name="description",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="photoessay",
            name="photo",
        ),
        migrations.AddField(
            model_name="photoessay",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="photo_essays/"),
        ),
    ]
