# Generated by Django 5.0.7 on 2024-07-15 16:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photography", "0003_rename_description_photoessay_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoessay",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
